[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.22"

[features]
seeds = false
skip-lint = false
[programs.localnet]
dune_staking_rewards_solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sotatek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
